### PR TITLE
Fix DisplayDuration display

### LINKED ISSUE #646: Bug: DurationDisplay formats several durations wrong
`TextUtilities.DisplayDuration` formats at least these duration values in a way, that the results are misleading:

* 60 sec -> 0.000 s
* 1 hour -> 0:00.000
* 2 days -> 0:00:00
* 1 second -> 0 ms

### PR DESCRIPTION
**Pull request by martin-strecker-sonarsource**
Fixes #646

`TextUtilities.DisplayDuration` produces invalid output for several different input values. The new tests executed against the old code produce the following test failures:
```
[xUnit.net 00:00:00.19]   Starting:    StructuredLogger.Tests
[xUnit.net 00:00:01.43]     StructuredLogger.Tests.TextUtilitiesTests.TestDisplayDuration(duration: 60000, expected: "1:00.000") [FAIL]
[xUnit.net 00:00:01.43]       Assert.Equal() Failure
[xUnit.net 00:00:01.43]                 ↓ (pos 0)
[xUnit.net 00:00:01.43]       Expected: 1:00.000
[xUnit.net 00:00:01.43]       Actual:   0.000 s
[xUnit.net 00:00:01.43]                 ↑ (pos 0)
[xUnit.net 00:00:01.45]     StructuredLogger.Tests.TextUtilitiesTests.TestDisplayDuration(duration: 172800040, expected: "2.00:00:00.0400000") [FAIL]
[xUnit.net 00:00:01.45]       Assert.Equal() Failure
[xUnit.net 00:00:01.45]                 ↓ (pos 0)
[xUnit.net 00:00:01.45]       Expected: 2.00:00:00.0400000
[xUnit.net 00:00:01.45]       Actual:   0:00:00
[xUnit.net 00:00:01.46]                 ↑ (pos 0)
[xUnit.net 00:00:01.46]     StructuredLogger.Tests.TextUtilitiesTests.TestDisplayDuration(duration: 3600000, expected: "01:00:00") [FAIL]
[xUnit.net 00:00:01.46]       Assert.Equal() Failure
[xUnit.net 00:00:01.46]                  ↓ (pos 1)
[xUnit.net 00:00:01.46]       Expected: 01:00:00
[xUnit.net 00:00:01.46]       Actual:   0:00.000
[xUnit.net 00:00:01.46]                  ↑ (pos 1)
[xUnit.net 00:00:01.46]     StructuredLogger.Tests.TextUtilitiesTests.TestDisplayDuration(duration: 1000, expected: "1.000 s") [FAIL]
[xUnit.net 00:00:01.46]       Assert.Equal() Failure
[xUnit.net 00:00:01.46]                 ↓ (pos 0)
[xUnit.net 00:00:01.46]       Expected: 1.000 s
[xUnit.net 00:00:01.46]       Actual:   0 ms
[xUnit.net 00:00:01.46]                 ↑ (pos 0)
[xUnit.net 00:00:01.46]     StructuredLogger.Tests.TextUtilitiesTests.TestDisplayDuration(duration: 172800000, expected: "2.00:00:00") [FAIL]
[xUnit.net 00:00:01.46]       Assert.Equal() Failure
[xUnit.net 00:00:01.46]                 ↓ (pos 0)
[xUnit.net 00:00:01.46]       Expected: 2.00:00:00
[xUnit.net 00:00:01.46]       Actual:   0:00:00
[xUnit.net 00:00:01.46]                 ↑ (pos 0)
[xUnit.net 00:00:01.46]   Finished:    StructuredLogger.Tests
========== Test run finished: 9 Tests (4 Passed, 5 Failed, 0 Skipped) run in 1,5 sec ==========
```

### CODE REVIEW

File: src/StructuredLogger/TextUtilities.cs [hunk 1]
```diff
@@ -451,18 +451,15 @@ public static string DisplayDuration(TimeSpan span, bool showZero = false)
             {
                 return showZero ? "0 ms" : "";
             }
-
-            if (span.TotalSeconds > 3600)
+            if (span.TotalHours >= 1)
             {
-                return span.ToString(@"h\:mm\:ss");
+                return span.ToString();
```
Comment (martin-strecker-sonarsource) [inline src/StructuredLogger/TextUtilities.cs:456]: Does this need to be stable? If so it might be better to specify the InvariantCulture.

Comment (KirillOsenkov) [reply src/StructuredLogger/TextUtilities.cs:456]: It's fine either way, it's for the user display only

**Review by KirillOsenkov — APPROVED** [review]
Oh wow thank you so much!

:+1:
